(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
(add-to-list 'default-frame-alist '(ns-appearance . dark))
(setq frame-resize-pixelwise t)
(setq powerline-image-apple-rgb t)
;;    (desktop-save-mode 1)
(setq desktop-path '("."))
;;    (setq desktop-save t)